version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout # check out the code in the project directory
      - run: ls -al
      - run: node --version
      - run: which npm
      - run: |
          npm install eslint
          ./node_modules/.bin/eslint .
